kind = "web"
previewPath = "/"
title = "MediBook Pro"
version = "1.0.0"
id = "artifacts/medibook-pro"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24501

[services.development]
run = "pnpm --filter @workspace/medibook-pro run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/medibook-pro", "run", "build" ]
publicDir = "artifacts/medibook-pro/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24501"
BASE_PATH = "/"
